baseURL = 'https://xandria-bv.web.app/'
title = 'Xandria Huisvesting'
theme = 'ananke'

defaultContentLanguage = 'nl'

[params]
  site_logo = "/images/logo.png"
  # Set this to your deployed Apps Script web app URL (or override per-shortcode)
  contactScriptURL = "https://script.google.com/macros/s/AKfycbw_YZFncG9G4tmUNkW_xlorfNn8lbaVjst7dFfgpVw6hw30j_7hRvcbCeJIOxH7OMFO/exec"
  # The secret is now read from the CONTACT_FORM_SECRET environment variable during build.

[languages]
  [languages.nl]
    languageName = 'Nederlands'
    languageCode = 'nl-NL'
    contentDir = 'content/nl' 
    weight = 1
  [languages.en]
    languageName = 'English'
    languageCode = 'en-US'
    contentDir = 'content/en' 
    weight = 2

[security]
  [security.funcs]
    getenv = ["^HUGO_", "^CI$", "CONTACT_FORM_SECRET"]