backend:
  name: github
  branch: main
  repo: ArdonToonstra/xandria
  base_url: https://decap-cms-backend-187698924322.europe-west1.run.app/
  site_domain: xandria-bv.web.app
  # Optional: restrict OAuth scopes (default includes repo access). Uncomment to set explicitly:
  # auth_scope: repo
  # client_id not needed when using self-hosted backend

  # If you prefer CMS to create pull requests instead of committing directly,
  # uncomment and set the following:
  # commit_mode: pull_request

# For production, disable the local backend. Local backend is for local testing only.
local_backend: false

# Waar afbeeldingen opgeslagen worden
media_folder: "static/images"
public_folder: "/images"

# Activeer meertaligheid
i18n:
  structure: multiple_folders
  locales: [nl] # De talen die je ondersteunt

collections:
  # Collectie voor de hoofdpagina's (Contact, Acquisitie)
  - name: "pages"
    label: "Pagina's"
    files:
      - file: "content/nl/contact.md"
        label: "Contact Pagina"
        name: "contact"
        i18n: false
        fields:
          - { label: "Titel", name: "title", widget: "string", i18n: false }
          - { label: "Publicatiedatum", name: "date", widget: "datetime", i18n: "duplicate" }
          - { label: "Inhoud", name: "body", widget: "markdown", i18n: false }
      - file: "content/nl/over-ons.md"
        label: "Over Ons Pagina"
        name: "over-ons"
        i18n: false
        fields:
          - { label: "Titel", name: "title", widget: "string", i18n: false }
          - { label: "Publicatiedatum", name: "date", widget: "datetime", i18n: "duplicate" }
          - { label: "Inhoud", name: "body", widget: "markdown", i18n: false }
      - file: "content/nl/panden.md"
        label: "Panden Pagina"
        name: "panden"
        i18n: false
        fields:
          - { label: "Titel", name: "title", widget: "string", i18n: false }
          - { label: "Publicatiedatum", name: "date", widget: "datetime", i18n: "duplicate" }
          - { label: "Inhoud", name: "body", widget: "markdown", i18n: false }

  # Collectie voor het verhuuraanbod
  - name: "te-huur"
    label: "Te Huur"
    folder: "content/nl/te-huur"
    create: true
    i18n: false
    slug: "{{slug}}"
    fields:
      - { label: "Titel", name: "title", widget: "string", i18n: false }
      - { label: "Status", name: "status", widget: "select", options: ["Beschikbaar", "Verhuurd", "Binnenkort beschikbaar", "Verhuurd"], i18n: false }
      - { label: "Type", name: "property_type", widget: "select", options: ["Appartement", "Huis", "Kantoor", "Garage", "Overig"], i18n: false, required: true }
      - { label: "Prijs (€/maand)", name: "price", widget: "number", i18n: false, required: false }
      - { label: "Adres", name: "address", widget: "string", i18n: false, required: false }
      - { label: "Oppervlakte (m²)", name: "surface", widget: "number", i18n: false, required: false }
      - { label: "Aantal kamers", name: "rooms", widget: "number", i18n: false, required: false }
      - { label: "Aantal slaapkamers", name: "bedrooms", widget: "number", i18n: false, required: false }
      - { label: "Tuin", name: "garden", widget: "boolean", i18n: false, required: false }
      - { label: "Balkon", name: "balcony", widget: "boolean", i18n: false, required: false }
      - { label: "Afbeeldingen", name: "images", widget: "image", media_library: { config: { multiple: true } }, i18n: false }
      - { label: "Kenmerken", name: "features", widget: "list", i18n: false, required: false, field: { label: "Kenmerk", name: "feature", widget: "string" } }
      - { label: "Vaste kosten (€)", name: "vaste_kosten", widget: "number", required: false, i18n: false }
      - { label: "Beschikbaar vanaf", name: "beschikbaar_vanaf", widget: "datetime", required: false, i18n: false }
      - { label: "EPC", name: "epc", widget: "string", required: false, i18n: false }
      - { label: "Staat", name: "staat", widget: "string", required: false, i18n: false }
      - { label: "Beglazing", name: "beglazing", widget: "string", required: false, i18n: false }
      - { label: "Verwarming", name: "verwarming", widget: "string", required: false, i18n: false }
      - { label: "Water", name: "water", widget: "string", required: false, i18n: false }
      - { label: "Mobiscore", name: "mobiscore", widget: "string", required: false, i18n: false }
      - { label: "Keuken", name: "keuken", widget: "string", required: false, i18n: false }
      - { label: "Badkamer", name: "badkamer", widget: "string", required: false, i18n: false }
      - { label: "Parkeerplaats", name: "parkeerplaats", widget: "string", required: false, i18n: false }
      - { label: "Lift", name: "lift", widget: "select", options: ["Ja", "Nee"], required: false, i18n: false }
      - { label: "Verdieping", name: "verdieping", widget: "string", required: false, i18n: false }
      - { label: "Huisdieren", name: "huisdieren", widget: "select", options: ["Toegestaan", "Niet toegestaan", "In overleg"], required: false, i18n: false }
      - { label: "Beschrijving", name: "body", widget: "markdown", i18n: false }